### ISSUE TITLE
Update meta.yml based on diffpy.snmf conda forge PR feedback

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/staged-recipes-cookiecutter#10]
We received feedback from the conda-forge reviewer on `diffpy.snmf`

https://github.com/conda-forge/staged-recipes/pull/27265

The major feedback is 

- that we want test whether need the `preserve_egg_dir: true` - this was a workaround for the namespace not getting clobbered
- add pip in requires in meta.yaml
- add `commands:` and `- pip check` in the tests action of meta.yaml
- put the sha directly in its place and don't put it at the top of the file and use jinja to template it.

Then, if needed, we shall update `meta.yaml` in here in `staged-recipes cookiecutter` , and updating the `meta.yaml` for all the projects already on conda-forge

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by bobleesj** [comment]
@sbillinge Seems like we have a bad player joined.

**Comment by bobleesj** [comment]
It was suggested by the diffpy.snmf conda-forge reviewer that we do not use SHA as a variable:

> We want to minimise the use of Jinja in conda-forge as this has regularly come up as a source of issues with the tooling we have built for conda-forge (mostly in smithy and the autotick bot). Thus if you use a value only once, don't put it in a jinja variable.

source: https://github.com/conda-forge/staged-recipes/pull/27265#discussion_r1736210779

I will try to make an update.

**Comment by bobleesj** [comment]
Closing this - all recommendations were implemented in https://github.com/Billingegroup/staged-recipes-cookiecutter/pull/11 and https://github.com/Billingegroup/staged-recipes-cookiecutter/pull/19 except `preserve_egg_dir=true`, the PR still being open.
