### ISSUE TITLE
How to ensure __version__ global variable is not 0.0.0 when imported (discussion)

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/staged-recipes-cookiecutter#20]
Since we had a `__version__` global variable set to `0.0.0` that was not detected by our CI system, how about we create a simple test function to address this?

The function would look like this:

```python
def test_package_version():
    """Ensure the package version is defined and not set to the initial placeholder."""
    assert hasattr(diffpy.utils, '__version__'), "The package version is not defined."
    assert diffpy.utils.__version__ != "0.0.0"
```

@sbillinge

**Comment by sbillinge** [comment]
This Lgtm. Is there a way to test it?

**Comment by bobleesj** [comment]
I will implement this first in `diffpy.structure` and then if it works then make a general change in the cookiecutter.
