### ISSUE TITLE
New conda-forge meta.yaml linting standards

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/staged-recipes-cookiecutter#28]
### Problem

A new warning message based on our current `meta.yaml` template is produced by the conda-forge-linter below:

---

For recipe/meta.yaml:

noarch: python recipes should almost always follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python). For the host section of the recipe, you should almost always use python {{ python_min }} for the python entry. For the run section of the recipe, you should almost always use python >={{ python_min }} for the python entry. For the test.requires section of the recipe, you should almost always use python {{ python_min }} for the python entry. You may need to override the python_min variable in the conda_build_config.yaml/variants.yaml if the package requires a newer Python version than the currently supported minimum version on conda-forge.
PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.

---

### Proposed solution:

Follow the conda-forge's recommended practice. Comments and changes are provided in one of our projects (bg-mpl-stylesheets): https://github.com/conda-forge/bg-mpl-stylesheets-feedstock/pull/29/files

If the above PR is merged, then I can update the current `meta.yaml` template here.

**Comment by sbillinge** [comment]
I merged that PR.  Go for it.
